FROM daocloud.io/node:8.11.1

MAINTAINER yuliang <yu.liang@freelog.com>

RUN mkdir -p /data/freelog-identity-provider

WORKDIR /data/freelog-identity-provider

COPY . /data/freelog-identity-provider

RUN npm install

ENV NODE_ENV test
ENV EGG_SERVER_ENV test
ENV PORT 5011

EXPOSE 5011

CMD [ "npm", "start" ]
